### ISSUE TITLE
Running on a Raspberry Pi Zero

### ISSUE THREAD

**Issue by gustavosilva-gss-zz** [contractorwolf/coronavirus-mask-detection#1]
I noticed you used a rasp pi 4 for the project, would the zero be able to do this? It's significantly weaker

**Comment by contractorwolf** [comment]
I think so as long as you were using the Google Coral for the main processing.  My guess is that your FPS would be longer but it is tough to guess by how much.  Good luck Gustavo.  BTW I think I blocked you on twitter because your account seemed suspicious, but I may unblock you now that I see why you are following me.
James

James Wolf
http://contractorwolf.com

"Worker bees can leave
Even drones can fly away
The queen is their slave"

________________________________

**Comment by gustavosilva-gss-zz** [comment]
I think i'll be getting into this project next week, thanks for the feedback. If I get it to work I'll let you know!
